[project]
name = "aired-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.26.0",
    "numpy>=2.4.4",
    "openai>=2.29.0",
    "openrouter>=0.7.11",
    "pandas>=3.0.2",
    "pyyaml>=6.0.2",
    "requests>=2.32.5",
]
